### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by mmikhasenko** [tamasgal/UnROOT.jl#157]
The newer version (`v0.8.3`, `v0.8.4`) of `UnROOT` does not compile on Windows throwing the error,
```julia
julia> using UnROOT
[ Info: Precompiling UnROOT [3cd96dde-e98d-4713-81e9-a4a1b0235ce9]
ERROR: LoadError: IOError: could not spawn `id -u`: no such file or directory (ENOENT)
Stacktrace:
[1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
```

I suppose it is caused by the [line](https://github.com/tamasgal/UnROOT.jl/blob/ad11fb6cd0005261ca3826a0dd20be6d91ec9501/src/streamsource.jl#L31)

```julia
uid = strip(read(`id -u`, String))
```

**Comment by tamasgal** [comment]
Aw, yeah that somehow slipped through, thanks!

**Comment by tamasgal** [comment]
@Moelf I am not sure if the user ID is necessary there or what the conventions are for the filename. Can we simply use a `tempfile()` there and append the `get(env, "USER")` or something like that? `tempfile()` would be needed anyways since `/tmp..` will fail on Windows either (I assume), but I am not really familiar with the Powershell semantics.

**Comment by Moelf** [comment]
Does GitHub have windows CI?

**Comment by tamasgal** [comment]
We can use AppVeyor or so: https://github.com/JuliaCI/Appveyor.jl

**Comment by Moelf** [comment]
actually, I don't think `scitoken` works on Windows... and I have never seen HEP using Windows, in fact ROOT doesn't even perfectly work on Windows

**Comment by Moelf** [comment]
>/tmp.. will fail on Windows either

this is specified by Scitoken spec, not up to me.

**Comment by tamasgal** [comment]
Ok perfectly fine with me 😜

**Comment by mmikhasenko** [comment]
thanks for the quick fix. It works
