### ISSUE TITLE
More accurate cache size determination and cache API

### ISSUE THREAD

**Issue by tamasgal** [tamasgal/UnROOT.jl#74]
Some recent discussions revealed that the memory footprint is a bit unpredictable and most probably dominated by the caching mechanism in `readbasketseek()`:

https://github.com/tamasgal/UnROOT.jl/blob/ac38c7505655ed92cae15d9f332223a6a0ac049f/src/root.jl#L417

- [ ] We need an API to give the user the possibility to tweak the cache (just like `uproot` does) and also
- [ ] refine the cache size calculation in `LRU` as it might be not accurate for nested objects.

Both points are low hanging fruits, so if you have any memory problems, you are welcome to help :)

**Comment by Moelf** [comment]
>refine the cache size calculation in LRU as it might be not accurate for nested objects.

complicated algorithm will slow down this by a lot. We can simply not have cache (other than the mandatory, latest-basket cache) by default, and allow user to turn on cache?

I know how to achieve certain objectives but I don't know what we **want**, because as it is now, it's unlikely to overrun users' memory, even though it's technically not 100% accurate.

Example objective: run over these files in single loop, limit peak memory to below XX; run over these files in parallel, limit peak memory to below XX.

**Comment by tamasgal** [comment]
Yes, I fully agree with your points.

I think that some utility functions like current estimated cache size and cache clearing is definitely something we need.

Regarding of the default settings, I think that caching should be part of it.

**Comment by Moelf** [comment]
There are some information from `TBranch` we may be able to use, I could try something later

**Comment by grasph** [comment]
Hello @Moelf and @tamasgal, I confirm that reducing the LRU cache has solved the memory issue I had.

Using a custom cache instead of '@memoize' sounds a good idea. Why do you need to cache more than the latest read Basket ?

**Comment by Moelf** [comment]
Two factors:
1. When user is doing stuff in interactive environment, they get much better experience, especially if the file lives on `/eos` where the speed is rather unreliable.
2. On top of 1., it doesn't slow down much even if it's "useless" (i.e. the total size in each loop is bigger than cache size).

Basically I aimed for something automatically make "quick check" work smooth while posing no danger to full-scale usage.

**Comment by grasph** [comment]
For the interactive environment, you mean in the case of use of an event loop, that will be repeated several times?  In the case of dataframe, the cache of baskets will be useless, as data will already be stored in the dataframe/typedtable. Am I correct?

Beware that implementing cache can be counterproductive. Indeed on Linux, the kernel uses the memory for the I/O buffer. So the memory used by the cache will be take from the one available for the kernel I/O buffer. On the other hand, data retrieved from I/O needs to be uncompressed, while in your own cache you can be uncompressed data.

Final remark, for interactive use case, you might prefer to cache the first N events instead of the last read ones. Indeed this will provide a good responsiveness, when testing the code with a limited number of events even after having make a run on the full sample.

**Comment by Moelf** [comment]
>as data will already be stored in the dataframe/typedtable. 

no, both `DataFrame` and our internal `TypedTable` are lazy, they only know the column's type and eltype. So this will benefit everything.

> while in your own cache you can be uncompressed data.

we are caching uncompressed data, that's what `readbasketseek` returns.

>Final remark, for interactive use case, you might prefer to cache the first N events instead of the last read ones. 

this is very true and we were talking about this, I will update this when I look at the cache very soon.
